### ISSUE TITLE
Cannot see rules within app

### ISSUE THREAD

**Issue by dl476375** [anonaddy/addy-ios#10]
Cannot see rules within addy.io ios app. Uploaded screenshot below. It errors out ![image](https://github.com/user-attachments/assets/87fc8a58-317e-423b-9abb-df4ac02c4f66)saying invalid format.

**Comment by willbrowningme** [comment]
Please could you provide more details and a screenshot if possible.

When you click on "Manage Rules" in the app are you shown a blank list?

**Comment by dl476375** [comment]
Here is screen shot

[image0.png]
Sent from my iPhone

On Oct 13, 2024, at 5:54 AM, Will Browning ***@***.***> wrote:

﻿
CAUTION: The Sender of this email is not from within Dalhousie.

Please could you provide more details and a screenshot if possible.

When you click on "Manage Rules" in the app are you shown a blank list?

**Comment by willbrowningme** [comment]
I'm afraid that image has not come through properly via email. You may need to comment via Github.com.

**Comment by dl476375** [comment]
![image](https://github.com/user-attachments/assets/62162815-b88b-482d-8bb5-b23249014d7e)

**Comment by dl476375** [comment]
Done.
Sent from my iPhone

On Oct 13, 2024, at 8:15 AM, Will Browning ***@***.***> wrote:

﻿
CAUTION: The Sender of this email is not from within Dalhousie.

I'm afraid that image has not come through properly via email. You may need to comment via Github.com.

**Comment by willbrowningme** [comment]
Thanks, please could you [send me an email](https://addy.io/contact/) with your username so I can check your account?

**Comment by Stjin** [comment]
@dl476375 Could you enable "store logs" in the app's settings, then go to this page and wait for this error to appear. Then go back to the "View stored logs" section within the app's settings. Tap the last error (assuming its the rules error) to share it. Then copy the output here?

**Comment by dl476375** [comment]
I turned on the logs and then went to rules. It did not generate any error logs.


Sent from my iPhone

On Oct 14, 2024, at 2:30 PM, Stjin ***@***.***> wrote:

﻿
CAUTION: The Sender of this email is not from within Dalhousie.

@dl476375<https://github.com/dl476375> Could you enable "store logs" in the app's settings, then go to this page and wait for this error to appear. Then go back to the "View stored logs" section within the app's settings. Tap the last error (assuming its the rules error) to share it. Then copy the output here?

**Comment by Stjin** [comment]
Hmm odd. I think there is an issue parsing your existing rules. Would you like to share the currently configured rules with me? Or, if you prefer to not share the rules publicly would it be okay for me to retrieve your set of rules rules through @willbrowningme by sending your username [through email?](https://addy.io/contact/)

I would love to fix this issue ASAP

**Comment by dl476375** [comment]
Yes i have already sent my username to his email.


Sent from my iPhone

On Oct 14, 2024, at 3:21 PM, Stjin ***@***.***> wrote:

﻿
CAUTION: The Sender of this email is not from within Dalhousie.

Hmm odd. I think there is an issue parsing your existing rules. Would you like to share the currently configured rules with me? Or, if you prefer to not share the rules publicly would it be okay for me to retrieve your set of rules rules through @willbrowningme<https://github.com/willbrowningme> by sending your username through email?<https://addy.io/contact/>

I would love to fix this issue ASAP

**Comment by Stjin** [comment]
Thanks for confirming! I will look at it ASAP and hope to fix it very soon. I will keep you updated!

Thanks for your bug report and I apologize for the "late" response from my side. I did not get notified of this issue 😅

**Comment by Stjin** [comment]
I have fixed the issue in PR https://github.com/anonaddy/addy-ios/pull/11
The update is being reviewed by Apple and _should_ arrive within the next 24-48 hours.

Sorry for the inconvenience.

Please let me know when you received the update and confirmed it is now working as expected
