### ISSUE TITLE
Montly bandwidth is not updated

### ISSUE THREAD

**Issue by dgnfunk** [anonaddy/addy-ios#16]
![image](https://github.com/user-attachments/assets/ef71829f-941f-49cf-b25d-be6bd1451c8b)

I’ve received a few forwarded mails and on the website is shown correctly but the app remains zero as rhe image.

**Comment by willbrowningme** [comment]
If you pull down to refresh do the numbers update?

**Comment by dgnfunk** [comment]
I see the problem, it’s a bit confusing between the we and the app, the later round the numbers.
